# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4e5bcb2c7f4b18bc3755b26cfccdddc7bcca3797975de5e7fda9b83738e81e43fb33b42824bfa88c3cc2a28ff9fd2b7ccadf8e32d4d00b50e003b7334fbc8cb

test:
  secret_key_base: cfbeef2836d9dfb8aa7e336f82cb4f3563ee38e56b78ee777aa075b9f4c426788779baf86e00e7a099f2b87da1d739c8161bcc26b80e574856aaf834b0c7a11c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
